---
- name: "Create generated-files directory"
  file:
    state: directory
    path: "generated-files"

- name: "Create {{app}} persistent volume claims"
  template: 
    src: "templates/persistent-volume-claim.yml.j2"
    dest: "generated-files/{{app}}-{{ item.name }}-pvc.yml"
  with_items: "{{volumes}}"
  when: volumes is defined and (volumes|length)>0

- name: "Create {{app}} configmaps"
  template: 
    src: templates/configmap.yml.j2
    dest: "generated-files/{{app}}-{{item.config_name}}-config.yml"
  with_items: "{{configmaps}}"
  when: configmaps is defined and (configmaps|length)>0

- name: "Create {{app}} secrets"
  template: 
    src: templates/secret.yml.j2
    dest: "generated-files/{{app}}-{{item.secret_name}}-secret.yml"
  with_items: "{{secrets}}"
  when: secrets is defined and (secrets|length)>0

- name: "Create {{app}} services"
  template: 
    src: templates/service.yml.j2
    dest: "generated-files/{{app}}-{{item.name}}-service.yml"
  with_items: "{{ports}}"
  when: ports is defined and (ports|length)>0

- name: "Create {{app}} image stream"
  template:
    src: templates/image-stream.yml.j2
    dest: "generated-files/{{ app }}-is.yml"
  when: "image_stream|default(false)|bool == true"

- name: "Create {{app}} deployment config"
  template:
    src: templates/deployment-config.yml.j2
    dest: "generated-files/{{ app }}-dc.yml"
  when: "deployment_config|default(false)|bool == true"

# only execute below this line when push_changes is true

- name: "Update {{app}} persistent volume claims"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "{{ item }}"
  with_items:
    - "generated-files/{{app}}-*-pvc.yml"
  when: "push_changes|default(false)|bool == true"

- name: "Update {{app}} image stream"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "generated-files/{{app}}-is.yml"
  when: "push_changes|default(false)|bool == true"

- name: "Update {{app}} configmaps"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "generated-files/{{app}}-*-config.yml"
  when: "push_changes|default(false)|bool == true"

- name: "Update {{app}} secrets"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "generated-files/{{app}}-*-secret.yml"
  when: "push_changes|default(false)|bool == true"

- name: "Update {{app}} deployment config"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "generated-files/{{app}}-dc.yml"
  when: "push_changes|default(false)|bool == true"

- name: "Update {{app}} services"
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "generated-files/{{ item }}"
  with_fileglob:
    - "generated-files/{{app}}-*-service.yml"
  when: "push_changes|default(false)|bool == true"

- name: delete generated-files dir
  file:
    path: generated-files
    state: absent
  when: "cleanup|default(false)|bool == true"

