---
- name: "Check {{ app }} teardown flag"
  debug:
    msg: "Teardown {{ app }}? {{ service_teardown|default(false)|bool }}"
  when: debug|default(false)|bool

- name: "Debug {{app}} k8s connection"
  debug:
    msg: |+
      host: {{ k8s_host }}
      username: {{ k8s_user }}
      namespace: {{ k8s_namespace }}
      verify_ssl: {{ k8s_verify_ssl }}
  when: debug|default(false)|bool

- name: "Include setup tasks for {{ app }}"
  include: setup.yml
  when: service_teardown|default(false)|bool == false

- name: "Include teardown tasks for {{ app }}"
  include: teardown.yml
  when: service_teardown|default(false)|bool == true

