---
- name: "Include setup tasks for {{ app }}"
  include: setup.yml
  when: service_teardown|default(false)|bool == false

- name: "Include teardown tasks for {{ app }}"
  include: teardown.yml
  when: service_teardown|default(false)|bool

