---
- name: Remove object definition
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    verify_ssl: "{{ k8s_verify_ssl|default(true) }}"
    username: "{{ k8s_user }}"
    state: absent
    definition:
      apiVersion: v1
      kind: "{{ item.kind }}"
      metadata:
        name: "{{ item.name|default(app) }}"
        namespace: "{{ namespace }}"
  with_items: "{{ items }}"
