---
- name: "Create {{ generated_files }} directory"
  file:
    state: directory
    path: "{{ generated_files }}"

- name: "Create {{namespace}}:{{app}} service account"
  template: 
    src: "templates/service-account.yml.j2"
    dest: "{{ generated_files }}/{{app}}-{{service_account}}-sa.yml"
  when: "service_account is defined"

- name: "Create {{namespace}}:{{app}} role bindings"
  template: 
    src: "templates/role-binding.yml.j2"
    dest: "{{ generated_files }}/{{app}}-{{ item.name }}-rb.yml"
  with_items: "{{default_rolebindings + rolebindings}}"
  when: "(default_rolebindings is defined) or (rolebindings is defined)"

- name: "Create {{namespace}}:{{app}} persistent volume claims"
  template: 
    src: "templates/persistent-volume-claim.yml.j2"
    dest: "{{ generated_files }}/{{app}}-{{ item.name }}-pvc.yml"
  with_items: "{{volumes}}"
  when: volumes is defined and (volumes|length)>0

- name: "Create {{namespace}}:{{app}} configmaps"
  template: 
    src: templates/configmap.yml.j2
    dest: "{{ generated_files }}/{{app}}-{{item.name}}-config.yml"
  with_items: "{{configmaps}}"
  when: configmaps is defined and (configmaps|length)>0

- name: "Create {{namespace}}:{{app}} secrets"
  template: 
    src: templates/secret.yml.j2
    dest: "{{ generated_files }}/{{app}}-{{item.name}}-secret.yml"
  with_items: "{{secrets}}"
  when: secrets is defined and (secrets|length)>0

- name: "Create {{namespace}}:{{app}} services"
  template: 
    src: templates/service.yml.j2
    dest: "{{ generated_files }}/{{app}}-{{item.name}}-service.yml"
  with_items: "{{ports}}"
  when: ports is defined and (ports|length)>0

- name: "Create {{namespace}}:{{app}} image stream"
  template:
    src: templates/image-stream.yml.j2
    dest: "{{ generated_files }}/{{ app }}-is.yml"
  when: "image_stream|default(false)|bool == true"

- name: "Create {{namespace}}:{{app}} deployment config"
  template:
    src: templates/deployment-config.yml.j2
    dest: "{{ generated_files }}/{{ app }}-dc.yml"
  when: "deployment_config|default(false)|bool == true"


- name: "Push object updates for {{ namespace }}:{{ app }}"
  include: update.yml
  when: "push_changes|default(false)|bool == true"


- name: delete {{ generated_files }} dir
  file:
    path: "{{ generated_files }}"
    state: absent
  when: "cleanup|default(false)|bool == true"

