---
- name: "Remove {{namespace}}:{{app}} deployment config"
  include: remove.yml
  vars:
    items:
      - kind: DeploymentConfig
      - kind: ReplicationController
  when: "deployment_config|default(false)|bool == true"

- name: "Remove {{namespace}}:{{app}} route"
  include: remove.yml
  vars:
    items:
      - kind: Route
  when: route|default(false)|bool

- name: "Remove {{namespace}}:{{app}} service account"
  include: remove.yml
  vars:
    items:
      - kind: ServiceAccount
        name: "{{ service_account }}"
  when: "service_account is defined"

- name: "Remove {{namespace}}:{{app}} image stream"
  include: remove.yml
  vars:
    items:
      - kind: ImageStream
  when: "image_stream|default(false)|bool == true"

- name: "Remove {{namespace}}:{{app}} services"
  include: remove.yml
  vars:
    items:
      - kind: Service
        name: "{{ item.name }}"
  with_items: "{{ports}}"
  when: ports is defined and (ports|length)>0

- name: "Remove {{namespace}}:{{app}} secrets"
  include: remove.yml
  vars:
    items:
      - kind: Secret
        name: "{{ item.name }}"
  with_items: "{{secrets}}"
  when: secrets is defined and (secrets|length)>0

- name: "Remove {{namespace}}:{{app}} configmaps"
  include: remove.yml
  vars:
    items:
      - kind: ConfigMap
        name: "{{ item.name }}"
  with_items: "{{configmaps}}"
  when: configmaps is defined and (configmaps|length)>0

- name: "Remove {{namespace}}:{{app}} persistent volume claims"
  include: remove.yml
  vars:
    items:
      - kind: PersistentVolumeClaim
        name: "{{ item.name }}"
  with_items: "{{volumes}}"
  when: volumes is defined and (volumes|length)>0

- name: "Remove {{namespace}}:{{app}} role bindings"
  include: remove.yml
  vars:
    items:
      - kind: RoleBinding
        name: "{{ item.name }}"
  with_items: "{{default_rolebindings + rolebindings}}"
  when: "(default_rolebindings is defined) or (rolebindings is defined)"

- name: "Remove {{namespace}}:{{app}} service account"
  include: remove.yml
  vars:
    items:
      - kind: ServiceAccount
        name: "{{ service_account }}"
  when: "service_account is defined"
