---
app: jenkins

image_stream: no
deployment_config: yes

image_name: jenkins
image_tag: "2"
# image_namespace: openshift
service_account: jenkins

res:
  - cpu: 512Mi
  - mem: 1Gi

ports:
  - name: jenkins
    port: 80
    target_port: 8080
    proto: TCP

  - name: jenkins-jnlp
    port: 50000
    target_port: 50000
    proto: TCP

volumes:
  - name: jenkins-data
    mount_path: /var/lib/jenkins
    storage_size: 1Gi

liveness_probe:
  failureThreshold: 2
  httpGet:
    path: /login
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 420
  periodSeconds: 360
  successThreshold: 1
  timeoutSeconds: 240

readiness_probe:
  failureThreshold: 3
  httpGet:
    path: /login
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 240
