---
- hosts: osio
  tasks:
  - name: remove objects
    k8s:
      host: "{{ k8s_host }}"
      api_key: "{{ k8s_api_key }}"
      username: "{{ k8s_user }}"
      state: absent
      definition:
        apiVersion: v1
        kind: "{{ item.kind }}"
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ k8s_namespace }}"
    with_items:
      - kind: DeploymentConfig
        name: webhook-server
      - kind: ImageStream
        name: webhook-server
      - kind: Service
        name: webhook
      - kind: PersistentVolumeClaim
        name: webhook-logs

- hosts: internal
  tasks:
  - name: remove objects
    k8s:
      host: "{{ k8s_host }}"
      api_key: "{{ k8s_api_key }}"
      username: "{{ k8s_user }}"
      state: absent
      definition:
        apiVersion: v1
        kind: "{{ item.kind }}"
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ k8s_namespace }}"
    with_items:
      - kind: DeploymentConfig
        name: webhook-client
      - kind: ImageStream
        name: webhook-client

