---
- hosts: operators
  vars_files:
    - vars/osio.yml
  vars:
    service_teardown: yes
  roles:
    - webhook-server

- hosts: operators
  vars_files:
    - vars/internal.yml
  vars:
    service_teardown: yes
  roles:
    - webhook-client
