---
- name: Create and update Indy objects
  import_role:
    name: openshift-simple-service
  vars:
    app: indy
    image_stream: yes
    image_from: Commonjava/indy

    deployment_config: yes
    ports:
      - name: http
        port: 80
        target_port: 8080
        proto: TCP

      - name: http-proxy
        port: 80
        target_port: 8081
        proto: TCP

    volumes:
      - name: indy-data
        mount_path: /opt/indy/var
        data_volume: indy-data
        storage_size: 1Gi
        storage_access: ReadWriteOnce

    configmaps:
      - config_name: indy-config
        mount_path: /opt/indy/etc/indy
        files:
        - files/main.conf

      - config_name: indy-logging-config
        mount_path: /opt/indy/etc/indy/logging
        files:
          - files/logging/logback.xml
