---
- name: create generated-files dir
  file:
    path: generated-files
    state: directory

- name: Create Indy objects
  template: 
    src: templates/indy-objects.yml.j2
    dest: generated-files/indy-objects.yml
  vars:
    data_volume: data
    config_volume: indy-config
    logging_config_volume: indy-logging-config

- name: generate-indy-config
  template: 
    src: templates/configmap.yml.j2
    dest: generated-files/indy-config.yml
  vars:
    config_name: indy-config
    files:
      - files/main.conf

- name: generate-indy-logging-config
  template: 
    src: templates/configmap.yml.j2
    dest: generated-files/indy-logging-config.yml
  vars:
    config_name: indy-logging-config
    files:
      - files/logging/logback.xml

- name: Update configs
  k8s:
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "generated-files/*.yml"
  when: push_changes

- name: delete generated-files dir
  file:
    path: generated-files
    state: absent
  when: push_changes
