---
- name: create generated-files dir
  file:
    path: generated-files
    state: directory

- name: Create Indy objects
  template: 
    src: "templates/{{ item }}.j2"
    dest: "generated-files/{{ item }}"
  vars:
    namespace: "{{ k8s_namespace }}"
    data_volume: data
    config_volume: indy-config
    logging_config_volume: indy-logging-config
  with_items:
    - 010-indy-pvc.yml
    - 020-indy-is.yml
    - 030-indy-dc.yml
    - 040-indy-httprox-service.yml
    - 050-indy-service.yml

- name: generate-indy-config
  template: 
    src: templates/configmap.yml.j2
    dest: generated-files/025-indy-config.yml
  vars:
    namespace: "{{ k8s_namespace }}"
    config_name: indy-config
    files:
      - files/main.conf

- name: generate-indy-logging-config
  template: 
    src: templates/configmap.yml.j2
    dest: generated-files/026-indy-logging-config.yml
  vars:
    namespace: "{{ k8s_namespace }}"
    config_name: indy-logging-config
    files:
      - files/logging/logback.xml

- name: Update basic objects
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "generated-files/{{ item }}"
  with_items:
    - 010-indy-pvc.yml
    - 020-indy-is.yml
  when: push_changes

- name: Update configmaps
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "generated-files/{{ item }}"
  with_items:
    - 025-indy-config.yml
    - 026-indy-logging-config.yml
  when: push_changes

- name: Update deployment config
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "generated-files/{{ item }}"
  with_items:
    - 030-indy-dc.yml
  when: push_changes

- name: Update services
  k8s:
    host: "{{ k8s_host }}"
    api_key: "{{ k8s_api_key }}"
    username: "{{ k8s_user }}"
    state: present
    src: "generated-files/{{ item }}"
  with_items:
    - 040-indy-httprox-service.yml
    - 050-indy-service.yml
  when: push_changes

- name: delete generated-files dir
  file:
    path: generated-files
    state: absent
  when: push_changes
